swagger: "2.0"
info:
  title: API de Avaliações
  description: API para upload de arquivos CSV e consulta de avaliações
  version: "1.0.0"

basePath: "/"
schemes:
  - http
  - https

tags:
  - name: Auth
    description: Geração de token JWT temporário
  - name: Arquivos
    description: Upload de arquivos CSV com avaliações
  - name: Avaliações
    description: Consulta de avaliações armazenadas no banco

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "Insira o token JWT como: Bearer <token>"

paths:
  /token:
    post:
      tags:
        - Auth
      summary: Gera um token temporário de acesso
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            example:
              usuario: exemplo
              perfil: admin
      responses:
        200:
          description: Token JWT gerado
          schema:
            type: object
            properties:
              token:
                type: string

  /upload:
    post:
      tags:
        - Arquivos
      summary: Realiza upload de arquivo CSV com avaliações
      consumes:
        - multipart/form-data
      security:
        - Bearer: []
      parameters:
        - in: formData
          name: file
          type: file
          required: true
          description: Arquivo CSV contendo avaliações
      responses:
        200:
          description: Lista de avaliações importadas
          schema:
            type: array
            items:
              $ref: "#/definitions/Avaliacao"
        400:
          description: Erro de validação (arquivo ausente ou inválido)
        500:
          description: Erro ao processar o CSV

  /avaliacoes:
    get:
      tags:
        - Avaliações
      summary: Retorna todas as avaliações salvas
      produces:
        - application/json
      security:
        - Bearer: []
      responses:
        200:
          description: Lista de avaliações
          schema:
            type: array
            items:
              $ref: "#/definitions/Avaliacao"

definitions:
  Avaliacao:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: João da Silva
      data:
        type: string
        format: date
        example: "2024-06-30"
      quarto:
        type: string
        example: Quarto 101
      avaliacao:
        type: string
        example: Muito bom
      nota:
        type: integer
        minimum: 0
        maximum: 10
        example: 9
